server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "refresh,health,info"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  application:
    name: demo-service

  kafka:
    bootstrap-servers: kafka:9092

  config:
    import: "configserver:http://config-server:8888"

  cloud:
    config:
      username: admin
      password: admin
      fail-fast: true
      retry:
        max-attempts: 12
        initial-interval: 1000
        max-interval: 20000
        multiplier: 1.5


  security:
    user:
      name: user
      password: password