#application.yml of config-server

server:
  port: 8888

spring:
  security:
    user:
      name: admin
      password: admin
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/raju4789/tourni-config.git
          clone-on-start: true
          default-label: main
  kafka:
    bootstrap-servers: kafka:9092



management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh,health,info"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always

